---
- name: configure uwsgi
  template:
    src: "{{ uwsgi_ini_tpl }}"
    dest: "{{ uwsgi_ini_path }}" 
  notify: reload uwsgi

- name: configure supervisor
  template:
    src: '{{ supervisor_conf_tpl }}'
    dest: '/etc/supervisor/conf.d/{{ program_name }}.conf'
  notify: reload supervisor
  become: true
  tags: superuser
